#!/usr/bin/env bash
#install and configure HAProxy on lb-01 server

sudo apt-get -y update
apt-get -y install haproxy


server_config=\
"
frontend  youssef-frontend
        bind *:80
        mode http
        default_backend amine-backend
backend amine-backend
        balance roundrobin
        server 364004-web-01 34.232.70.0:80 check
        server 364004-web-02 54.89.195.107:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
