#!/usr/bin/env bash
#install and configure HAProxy on lb-01 server

sudo apt-get -y update
apt-get -y install haproxy


server_config=\
"
frontend  amine-frontend
        bind *:80
        mode http
        default_backend amine-backend
backend amine-backend
        balance roundrobin
        server 63210-web-01 54.205.163.79:80 check
        server 63210-web-02 100.26.250.253:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
